Create Interfaces
brunnacroches/ifood_mongo_db pull request #2
Opened 2023-05-25 19:50 UTC by brunnacroches

2023-05-25 22:14 UTC, programadorLhama requested changes

2023-05-25 22:14 UTC, programadorLhama commented on src/controllers/interface/controller_interface.py
> +        pass
Fazer interfaces especificas para controllers

2023-05-25 22:16 UTC, programadorLhama requested changes

2023-05-25 22:16 UTC, programadorLhama commented on run.py
>  db_hanlde = DBConnectionHandler()
Colocar antes da função if __name__ == '__main__':

2023-05-25 22:16 UTC, programadorLhama commented on src/controllers/search_product_controller.py
> +        pass
Retirar metodo generico nos controllers

2023-05-27 22:22 UTC, brunnacroches commented on run.py
>  db_hanlde = DBConnectionHandler()
feito!

2023-05-27 23:09 UTC, merged